apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  namespace: mongo-express 
  labels:
    app: mongo-express 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: mongo-express-config
        env:
        - name: ME_CONFIG_MONGODB_URL
          value: "mongodb://admin:admin123@mongodb-service.mongo-db.svc.cluster.local:27017/admin"
       