apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-only-mongo-express
  namespace: mongo-db  
spec:
  podSelector: {}       
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: mongo-express
    ports:
    - protocol: TCP
      port: 27017