apiVersion: v1
kind: Service
metadata:
  name: fe-service
  namespace: fe 
spec:
  type: NodePort
  selector:
    app: fe
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009